FROM golang:latest AS builder

WORKDIR /build

ADD go.mod .

COPY ./ /build

COPY /config/.env /app/

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/main /build/main.go

FROM alpine

WORKDIR /app

COPY --from=builder /app/.env /app/.env
COPY --from=builder /app/main /app/main

CMD ["/app/main"]
